# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

r_packages:
 - devtools

r_github_packages:
  - r-lib/covr

sudo: required

before_install:
 - cd r-package
 - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev unrar-free
 - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

after_success:
  - travis_wait 120 Rscript -e 'covr::codecov()'
  
os:
  - linux
  
Comment:
  - osx
