# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
install: travis_wait mvn install
apt_packages:
  - libudunits2-dev 
  - libgdal-dev 
  - libgeos-dev 
  - libproj-dev 

after_success:
  - travis_wait 120 Rscript -e 'covr::codecov()'
  - travis_wait 120 Rscript -e 'pkgdown::build_site()'
  
os:
  - linux
  
Comment:
  - osx
